const adminPages=[['index','Dashboard'],['sellers','Sellers'],['users','Users'],['products','Products'],['orders','Orders'],['payments','Payments'],['returns','Returns'],['tickets','Support'],['wallet','Settlements'],['logistics','Logistics'],['campaigns','Campaigns'],['notifications','Notifications'],['analytics','Analytics'],['risk','Risk'],['audit','Audit log'],['settings','Settings'],['policies','Policies'],['launch','Readiness']];
const adminPage=location.pathname.split('/').pop()||'index.html';
function feedback(message,error=false){
  let box=document.getElementById('adminFeedback');
  if(!box){box=document.createElement('div');box.id='adminFeedback';box.setAttribute('role','status');(document.querySelector('main')||document.body).prepend(box)}
  box.className=error?'feedback error':'feedback';box.textContent=message;box.hidden=false;
}
function adminBack(){
  const stack=JSON.parse(sessionStorage.getItem('pm_admin_history')||'[]');
  stack.pop();const previous=stack.pop();sessionStorage.setItem('pm_admin_history',JSON.stringify(stack));
  location.href=adminPages.some(([p])=>p+'.html'===previous)?previous:'index.html';
}
function initAdminShell(){
  const nav=document.querySelector('aside nav');if(!nav)return;
  nav.innerHTML=adminPages.map(([p,label])=>`<a href="${p}.html" ${adminPage===p+'.html'?'class="active" aria-current="page"':''}>${label}</a>`).join('');
  try{let history=JSON.parse(sessionStorage.getItem('pm_admin_history')||'[]');if(history.at(-1)!==adminPage)history.push(adminPage);sessionStorage.setItem('pm_admin_history',JSON.stringify(history.slice(-30)))}catch(e){sessionStorage.removeItem('pm_admin_history')}
  const header=document.querySelector('header');
  const toolbar=document.createElement('div');toolbar.className='admin-toolbar';
  toolbar.innerHTML=`<button type="button" class="soft" title="Back" aria-label="Back" onclick="adminBack()">&#8592;</button><span>Admin / ${esc(adminPages.find(([p])=>p+'.html'===adminPage)?.[1]||'Dashboard')}</span><a href="index.html" title="Dashboard">Dashboard</a><button class="soft" onclick="logout()">Sign out</button>`;
  header.prepend(toolbar);
  const menu=document.createElement('button');menu.className='soft mobile-menu';menu.textContent='Menu';menu.setAttribute('aria-expanded','false');menu.onclick=()=>{const open=document.querySelector('aside').classList.toggle('menu-open');menu.setAttribute('aria-expanded',String(open))};toolbar.prepend(menu);
  document.querySelectorAll('table').forEach(table=>{const wrap=document.createElement('div');wrap.className='table-scroll';wrap.tabIndex=0;wrap.setAttribute('role','region');wrap.setAttribute('aria-label','Scrollable data table');table.before(wrap);wrap.append(table)});
  document.querySelectorAll('a[target="_blank"]').forEach(a=>a.rel='noopener noreferrer');
}
let sellersData=[];
window.loadSellers=async function(){
  sellersData=(await api('/api/admin/sellers')).sellers||[];
  let controls=document.getElementById('sellerControls');
  if(!controls){controls=document.createElement('div');controls.id='sellerControls';controls.className='seller-controls';controls.innerHTML='<input id="sellerSearch" aria-label="Search sellers" placeholder="Search name, shop or email"><select id="sellerFilter" aria-label="Seller status"><option value="all">All sellers</option><option value="pending">Pending</option><option value="approved">Approved</option><option value="rejected">Rejected</option><option value="suspended">Suspended</option></select><span id="sellerCount"></span>';document.querySelector('main').prepend(controls);controls.addEventListener('input',renderSellers)}
  renderSellers();
};
function renderSellers(){
  const query=document.getElementById('sellerSearch').value.toLowerCase().trim(),filter=document.getElementById('sellerFilter').value;
  const rows=sellersData.filter(s=>(filter==='all'||(filter==='suspended'?s.status==='suspended':s.seller_status===filter))&&[s.name,s.shop_name,s.email,s.id].join(' ').toLowerCase().includes(query));
  document.getElementById('sellerCount').textContent=`${rows.length} of ${sellersData.length} sellers`;
  document.getElementById('tbody').innerHTML=rows.map(s=>`<tr><td>#${s.id}</td><td><b>${esc(s.shop_name||s.name)}</b><div>${esc(s.name)}</div><div class="muted">${esc(s.email)}<br>${esc(s.phone||'')}</div><details><summary>Verification details</summary><p>Business: ${esc(s.business_type||'Not supplied')}<br>SSM: ${esc(s.ssm_number||'Not supplied')}<br>SSM status: ${esc(s.business_verification_status||'not_submitted')}</p>${safeDocumentLink(s.ssm_document_url)}<p>Identity: ${esc(s.identity_type)} ${esc(s.identity_number)}<br>Bank: ${esc(s.bank_name)} / ${esc(s.bank_account_name)} / ${esc(s.bank_account_number)}</p><button class="soft" onclick="setBusiness(${s.id},'verified')">Verify SSM</button> <button class="danger" onclick="setBusiness(${s.id},'rejected')">Reject SSM</button></details></td><td><span class="tag ${s.seller_status==='approved'?'ok':s.seller_status==='rejected'?'bad':''}">${esc(s.seller_status)}</span></td><td>${esc(s.status)}</td><td><div class="actions">${s.seller_status!=='approved'?`<button class="primary" onclick="reviewSeller(${s.id},'approved')">Review &amp; approve</button>`:s.status==='suspended'?`<button class="primary" onclick="setUser(${s.id},'active','approved')">Reactivate account</button>`:'<span class="tag ok">Approved</span>'}${s.seller_status==='pending'?`<button class="danger" onclick="reviewSeller(${s.id},'rejected')">Reject application</button>`:''}${s.seller_status==='approved'&&s.status==='active'?`<button class="danger" onclick="suspendSeller(${s.id})">Suspend account</button>`:''}</div></td></tr>`).join('')||'<tr><td colspan="5">No sellers match your search.</td></tr>';
}
function safeDocumentLink(value){try{const url=new URL(value);return ['https:','http:'].includes(url.protocol)?`<a href="${esc(url.href)}" target="_blank" rel="noopener noreferrer">View SSM document</a>`:''}catch{return ''}}
function reviewSeller(id,decision){
  const seller=sellersData.find(s=>s.id===id);if(!seller)return;
  document.getElementById('sellerDecision')?.remove();
  const modal=document.createElement('dialog');modal.id='sellerDecision';
  modal.innerHTML=`<form><h3>${decision==='approved'?'Approve':'Reject'} seller application</h3><p><b>${esc(seller.shop_name||seller.name)}</b><br>${esc(seller.email)}</p><label>Reason / note ${decision==='rejected'?'(required)':'(optional)'}<textarea id="decisionReason" maxlength="2000" ${decision==='rejected'?'required':''}></textarea></label><p class="muted">The seller will receive your decision by email.</p><p id="decisionError" role="alert"></p><div class="actions"><button type="button" class="soft" id="decisionBack">Back</button><button type="submit" class="${decision==='approved'?'primary':'danger'}">Confirm ${decision==='approved'?'approval':'rejection'}</button></div></form>`;
  document.body.append(modal);modal.querySelector('#decisionBack').onclick=()=>modal.close();
  modal.querySelector('form').onsubmit=async event=>{event.preventDefault();const reason=modal.querySelector('textarea').value.trim();if(decision==='rejected'&&!reason){modal.querySelector('#decisionError').textContent='A rejection reason is required.';return}const button=modal.querySelector('[type=submit]');button.disabled=true;try{await api('/api/admin/user-status',{method:'POST',body:JSON.stringify({user_id:id,status:decision==='approved'?'active':'suspended',seller_status:decision,reason})});modal.close();feedback(`Seller ${decision}. Decision email queued.`);await loadSellers();await loadNotificationBadges()}catch(e){modal.querySelector('#decisionError').textContent=e.message}finally{button.disabled=false}};modal.showModal();
}
async function suspendSeller(id){if(!confirm('Suspend this seller account? This blocks seller login without rejecting the application.'))return;await setUser(id,'suspended','approved')}
window.setUser=async function(id,status,seller_status){if(pendingUserUpdates.has(id))return;pendingUserUpdates.add(id);try{await api('/api/admin/user-status',{method:'POST',body:JSON.stringify({user_id:id,status,seller_status})});feedback('Account status updated.');if(adminPage==='sellers.html')await loadSellers();else await loadUsers();await loadNotificationBadges()}catch(e){feedback(e.message,true)}finally{pendingUserUpdates.delete(id)}};
window.login=async function(){const message=document.getElementById('status');try{message.textContent='Signing in...';const d=await api('/api/auth/login',{method:'POST',body:JSON.stringify({email:document.getElementById('email').value.trim(),password:document.getElementById('password').value})});if(d.user?.role!=='admin')throw new Error('Admin access required');localStorage.setItem('pm_admin_token',d.token);localStorage.setItem('pm_admin_user',JSON.stringify(d.user));location.href='index.html'}catch(e){message.textContent=e.message}};
window.adminMoveOrder=async function(order_id,order_status){const tracking=prompt('Tracking / admin note, leave blank to keep current','');if(tracking===null)return;const body={order_id,order_status};if(tracking)body.tracking_no=tracking;await api('/api/orders/status',{method:'POST',body:JSON.stringify(body)});await loadOrders();feedback('Order updated.')};
window.cancelPendingPayment=async function(order_id){const note=prompt('Cancel/expire note','Admin cancelled stale unpaid order');if(note===null)return;await api('/api/admin/payment-cancel',{method:'POST',body:JSON.stringify({order_id,note})});if(adminPage==='orders.html')await loadOrders();else await loadPayments();feedback('Unpaid order cancelled.')};
window.saveSettings=async function(){const settings={};document.querySelectorAll('#settingsBox input').forEach(i=>settings[i.id.replace('set_','')]=i.value);await api('/api/admin/settings',{method:'POST',body:JSON.stringify({settings})});document.getElementById('status').textContent='Settings saved.';feedback('Settings saved.')};
window.loadUsers=async function(){const rows=(await api('/api/admin/users')).users||[];document.getElementById('tbody').innerHTML=rows.map(u=>`<tr><td>#${u.id}</td><td><b>${esc(u.name)}</b><div class="muted">${esc(u.email)}</div></td><td>${esc(u.role)}</td><td>${esc(u.status)}</td><td>${esc(u.seller_status)}</td><td>${u.role==='seller'?'<a class="soft" href="sellers.html">Review seller</a>':`<button class="soft" onclick="setUser(${Number(u.id)},'active','not_applicable')">Enable account</button> <button class="danger" onclick="setUser(${Number(u.id)},'suspended','not_applicable')">Suspend account</button>`}</td></tr>`).join('')||'<tr><td colspan="6">No users found.</td></tr>'};
window.setPayout=async function(wallet_id,status,proof=false){
  if(!proof){if(!confirm(`Change settlement #${wallet_id} to ${status}?`))return;await api('/api/admin/payout-status',{method:'POST',body:JSON.stringify({wallet_id,status,note:`Admin marked payout ${status}`})});await loadWallet();feedback('Settlement updated.');return}
  const payout_reference=prompt('Enter payout bank reference number');if(payout_reference===null)return;if(!payout_reference.trim())throw new Error('A payout bank reference is required.');
  const date=prompt('Paid date YYYY-MM-DD, leave empty for now','');if(date===null)return;const payout_paid_at=date?Math.floor(new Date(date+'T12:00:00').getTime()/1000):0;if(date&&(!/^\d{4}-\d{2}-\d{2}$/.test(date)||!Number.isFinite(payout_paid_at)))throw new Error('Enter a valid paid date.');
  const input=document.createElement('input');input.type='file';input.accept='image/*,.pdf';input.onchange=async()=>{if(!input.files?.[0])return;try{const payout_proof_url=await uploadPayoutProof(input.files[0]);await api('/api/admin/payout-status',{method:'POST',body:JSON.stringify({wallet_id,status,payout_proof_url,payout_reference,payout_paid_at,note:`Admin marked payout ${status}`})});await loadWallet();feedback('Settlement marked paid.')}catch(e){feedback(e.message,true)}};input.click();
};
window.exportAudit=function(){const cols=['id','actor_id','action','target_type','target_id','note','created_at'];const csv=[cols.join(',')].concat(auditFiltered.map(r=>cols.map(c=>'"'+String(r[c]??'').replace(/"/g,'""')+'"').join(','))).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='pasarmalam-audit.csv';a.click();URL.revokeObjectURL(a.href)};
window.logout=function(){['pm_admin_token','pm_admin_user'].forEach(k=>localStorage.removeItem(k));if(user().role==='admin'){localStorage.removeItem('pm_token');localStorage.removeItem('pm_user')}sessionStorage.removeItem('pm_admin_history');location.href='login.html'};
for(const name of ['loadMetrics','loadAnalytics','loadRisk','loadLaunchReadiness','loadUsers','loadSellers','loadProducts','loadOrders','loadPayments','loadReturns','loadTickets','loadLogistics','loadWallet','loadCampaigns','loadSettings','loadAudit','setBusiness','setProduct','adminMoveOrder','reviewPayment','cancelPendingPayment','setReturn','updateTicket','setPayout','saveSettings','changeAdminPassword']){
  const action=window[name];if(!action)continue;
  window[name]=async function(...args){const button=!name.startsWith('load')&&document.activeElement?.tagName==='BUTTON'?document.activeElement:null;if(button?.disabled)return;try{if(button)button.disabled=true;return await action(...args)}catch(e){feedback(e.message||'Request failed. Please retry.',true)}finally{if(button)button.disabled=false}};
}
window.addEventListener('unhandledrejection',event=>{feedback(event.reason?.message||'Request failed. Please retry.',true);event.preventDefault()});
initAdminShell();
