const API="https://pasarmalam-backend.onrender.com";
function token(){return localStorage.getItem("pm_admin_token")||localStorage.getItem("pm_token")||""}
function user(){try{return JSON.parse(localStorage.getItem("pm_admin_user")||localStorage.getItem("pm_user")||"{}")}catch{return {}}}
async function api(path,options={}){const headers={"Content-Type":"application/json",...(options.headers||{})};const t=token();if(t)headers.Authorization=`Bearer ${t}`;const r=await fetch(API+path,{...options,headers});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Request failed");return d}
function money(v){return `RM${Number(v||0).toFixed(2)}`}
function esc(v){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[m]))}
function requireAdmin(){const u=user();if(!token()||u.role!=="admin")location.href="login.html"}
async function login(){const d=await api("/api/auth/login",{method:"POST",body:JSON.stringify({email:email.value,password:password.value})});if(d.user?.role!=="admin"){status.textContent="Admin access required";return}localStorage.setItem("pm_admin_token",d.token);localStorage.setItem("pm_admin_user",JSON.stringify(d.user));location.href="index.html"}
function logout(){localStorage.removeItem("pm_admin_token");localStorage.removeItem("pm_admin_user");location.href="login.html"}
async function loadMetrics(){const m=await api("/api/admin/metrics");metrics.innerHTML=`<div class="stat"><span>Users</span><b>${m.users}</b></div><div class="stat"><span>Products</span><b>${m.products}</b></div><div class="stat"><span>Orders</span><b>${m.orders}</b></div><div class="stat"><span>Sales</span><b>${money(m.sales)}</b></div><div class="stat"><span>Buyers</span><b>${m.buyers}</b></div><div class="stat"><span>Sellers</span><b>${m.sellers}</b></div><div class="stat"><span>Returns</span><b>${m.returns}</b></div><div class="stat"><span>Campaigns</span><b>${m.campaigns}</b></div>`}
async function loadAnalytics(){const a=await api("/api/admin/analytics");orderStatus.innerHTML=a.order_status.map(x=>`<div class="item"><b>${x.order_status}</b><span class="muted"> ${x.count} orders | ${money(x.sales)}</span></div>`).join("")||"<p class='muted'>No orders.</p>";categories.innerHTML=a.product_categories.map(x=>`<div class="item"><b>${esc(x.category)}</b><span class="muted"> ${x.count} listings | ${x.sold} sold</span></div>`).join("");sellerRank.innerHTML=a.seller_rank.map(x=>`<tr><td>${esc(x.shop)}</td><td>${x.orders}</td><td>${money(x.sales)}</td></tr>`).join("");returnRate.textContent=a.return_rate+'%'}
async function loadUsers(){const rows=(await api("/api/admin/users")).users;tbody.innerHTML=rows.map(u=>`<tr><td>${u.id}</td><td><b>${esc(u.name)}</b><div class="muted">${esc(u.email)}</div></td><td>${u.role}</td><td><span class="tag ${u.status==="active"?"ok":"bad"}">${u.status}</span></td><td>${u.seller_status}</td><td><button class="soft" onclick="setUser(${u.id},'active','${u.seller_status}')">Activate</button> <button class="danger" onclick="setUser(${u.id},'suspended','${u.seller_status}')">Suspend</button></td></tr>`).join("")}
async function loadSellers(){const rows=(await api("/api/admin/sellers")).sellers;tbody.innerHTML=rows.map(u=>`<tr><td>${u.id}</td><td><b>${esc(u.shop_name||u.name)}</b><div class="muted">${esc(u.email)} | ${esc(u.phone)}</div><div class="muted">Owner: ${esc(u.name)} | ${esc(u.identity_type)} ${esc(u.identity_number)}</div><div class="muted">Business: ${esc(u.business_type||"not added")} | SSM ${esc(u.ssm_number||"not added")} | <b>${esc(u.business_verification_status||"not_submitted")}</b></div><div class="muted">${u.ssm_document_url?`<a href="${esc(u.ssm_document_url)}" target="_blank">View SSM document</a>`:"No SSM document uploaded"}</div><div class="muted">Payout: ${esc(u.bank_name)} | ${esc(u.bank_account_name)} | ${esc(u.bank_account_number)}</div></td><td><span class="tag ${u.seller_status==="approved"?"ok":""}">${u.seller_status}</span></td><td><span class="tag ${u.status==="active"?"ok":"bad"}">${u.status}</span></td><td><button class="soft" onclick="setUser(${u.id},'active','approved')">Approve Seller</button> <button class="danger" onclick="setUser(${u.id},'suspended','rejected')">Reject/Suspend</button><br><button class="soft" onclick="setBusiness(${u.id},'verified')">Verify SSM</button> <button class="danger" onclick="setBusiness(${u.id},'rejected')">Reject SSM</button></td></tr>`).join("")}
async function setUser(id,status,seller_status){await api("/api/admin/user-status",{method:"POST",body:JSON.stringify({user_id:id,status,seller_status})});location.reload()}
async function setBusiness(id,business_verification_status){await api("/api/admin/business-verification",{method:"POST",body:JSON.stringify({user_id:id,business_verification_status})});location.reload()}
async function loadProducts(){const rows=(await api("/api/admin/products")).products;tbody.innerHTML=rows.map(p=>{const img=(p.images&&p.images[0])||p.image_url||"";return `<tr><td>${img?`<img class="thumb" src="${img}">`:""}<b>${esc(p.name)}</b><div class="muted">${esc(p.shop)} | ${esc(p.category)}</div></td><td>${money(p.price)}</td><td>${p.stock}</td><td>${p.condition}</td><td><span class="tag ${p.moderation_status==="approved"?"ok":"bad"}">${p.moderation_status||"approved"}</span></td><td><button class="soft" onclick="setProduct(${p.id},'approved')">Approve</button> <button class="danger" onclick="setProduct(${p.id},'hidden')">Hide</button></td></tr>`}).join("")}
async function setProduct(id,moderation_status){await api("/api/admin/product-status",{method:"POST",body:JSON.stringify({product_id:id,moderation_status})});location.reload()}
async function loadOrders(){const rows=(await api("/api/admin/orders")).orders;tbody.innerHTML=rows.map(o=>`<tr><td>PM-${o.id}</td><td>${esc(o.product_name)}<div class="muted">${esc(o.seller_shop)}</div></td><td>${esc(o.buyer_name)}</td><td>${money(o.total)}</td><td><b>${o.payment_status}</b>${o.payment_proof_url?`<div><a href="${o.payment_proof_url}" target="_blank">View receipt</a></div>`:""}</td><td><span class="tag">${o.order_status}</span></td><td>${o.payment_status==="pending_review"?`<button class="soft" onclick="reviewPayment(${o.id},'paid')">Approve</button> <button class="danger" onclick="reviewPayment(${o.id},'rejected')">Reject</button>`:esc(o.tracking_no)}</td></tr>`).join("")}
async function reviewPayment(order_id,payment_status){await api("/api/admin/payment-status",{method:"POST",body:JSON.stringify({order_id,payment_status,note:"Manual payment proof checked"})});location.reload()}
async function loadReturns(){const rows=(await api("/api/admin/returns")).returns;tbody.innerHTML=rows.map(r=>`<tr><td>${r.id}</td><td>PM-${r.order_id}<div class="muted">${esc(r.product_name||"")}</div></td><td>${esc(r.buyer_name)}</td><td>${esc(r.reason)}${r.evidence_url?`<div><a href="${r.evidence_url}" target="_blank">Evidence</a></div>`:""}</td><td><span class="tag">${r.status}</span><div class="muted">${r.dispute_status||"open"}</div></td><td><button class="soft" onclick="setReturn(${r.id},'approved','resolved')">Approve</button> <button class="danger" onclick="setReturn(${r.id},'rejected','closed')">Reject</button> <button class="soft" onclick="setReturn(${r.id},'refunded','closed')">Mark Refunded</button></td></tr>`).join("")}
async function setReturn(id,status,dispute_status){await api("/api/admin/return-status",{method:"POST",body:JSON.stringify({return_id:id,status,dispute_status,seller_response:"Admin reviewed"})});location.reload()}
async function loadTickets(){const d=await api("/api/admin/tickets");messages.innerHTML=d.messages.map(m=>`<div class="item"><b>${esc(m.sender_role)}: ${esc(m.buyer_name||m.seller_name)}</b><p>${esc(m.body)}</p><span class="muted">Product ${m.product_id||"-"}</span></div>`).join("")||"<p class='muted'>No messages.</p>";disputes.innerHTML=d.open_disputes.map(r=>`<div class="item"><b>Return ${r.id} | Order PM-${r.order_id}</b><p>${esc(r.reason)}</p><span class="tag">${r.dispute_status||"open"}</span></div>`).join("")||"<p class='muted'>No open disputes.</p>"}
async function loadLogistics(){const d=await api("/api/admin/logistics");tbody.innerHTML=d.rates.map(r=>`<tr><td>${r.method}</td><td>${money(r.fee)}</td><td>${r.eta}</td><td>${r.tracking?"Tracking":"Own/manual"}</td><td><span class="tag ${r.enabled?"ok":"bad"}">${r.enabled?"enabled":"off"}</span></td></tr>`).join("");summary.innerHTML=`<div class="item"><b>AWB Prefix</b><p>${d.awb_prefix}</p></div><div class="item"><b>Mass Shipping</b><p>${d.mass_shipping?"Enabled":"Off"}</p></div><div class="item"><b>Return Shipping Review</b><p>${d.return_shipping_review?"Enabled":"Off"}</p></div>`}
function escrowLabel(s){return {holding:"Holding",released:"Released",dispute_hold:"Dispute hold",refund_approved:"Refund approved",refund_rejected:"Refund rejected",refunded:"Refunded",cancelled:"Cancelled",pending:"Pending"}[s]||s}
function payoutLabel(s){return {pending:"Pending",approved:"Approved",paid_out:"Paid out",held:"Held",rejected:"Rejected"}[s]||s}
let walletExportRows=[];
async function loadWallet(){const d=await api("/api/wallet");const rows=d.wallet||[],s=d.summary||{};walletExportRows=rows;walletSummary.innerHTML=`<div class="stat"><span>Gross Sales</span><b>${money(s.gross)}</b></div><div class="stat"><span>Commission</span><b>${money(s.commission)}</b></div><div class="stat"><span>Seller Earnings</span><b>${money(s.seller_earning)}</b></div><div class="stat"><span>Pending Payout</span><b>${money(s.pending)}</b></div><div class="stat"><span>Approved</span><b>${money(s.approved)}</b></div><div class="stat"><span>Paid Out</span><b>${money(s.paid_out)}</b></div><div class="stat"><span>Held</span><b>${money(s.held)}</b></div>`;tbody.innerHTML=rows.map(w=>{const blocked=["dispute_hold","refund_approved","refunded","cancelled"].includes(w.escrow_status);const escrowText=escrowLabel(w.escrow_status);const finalRefund=w.escrow_status==="refunded";const actions=blocked?`<span class="tag bad">${finalRefund?"Refunded - payout blocked":"Payout blocked"}</span><div class="muted">Escrow: ${esc(escrowText)}</div><button class="danger" onclick="setPayout(${w.id},'held')">Keep Held</button>`:`<button class="soft" onclick="setPayout(${w.id},'approved')">Approve</button> <button class="soft" onclick="setPayout(${w.id},'paid_out',true)">Mark Paid</button> <button class="danger" onclick="setPayout(${w.id},'held')">Hold</button>`;return `<tr><td>#${w.id}<div class="muted">PM-${w.order_id||"-"} | ${new Date((w.created_at||0)*1000).toLocaleString()}</div>${finalRefund?'<div class="tag bad">Refunded</div>':""}</td><td><b>${esc(w.shop_name||w.seller_name||"Seller")}</b><div class="muted">${esc(w.bank_name||"")} | ${esc(w.bank_account_name||"")} | ${esc(w.bank_account_number||"")}</div></td><td>${money(w.gross_amount||w.amount)}</td><td>${w.commission_rate||0}%<div class="muted">${money(w.commission_amount)}</div></td><td><b>${money(w.seller_earning||w.amount)}</b></td><td><span class="tag ${w.status==="paid_out"?"ok":w.status==="rejected"||blocked?"bad":""}">${payoutLabel(w.status)}</span><div class="muted">${esc(w.note||"")}</div><div class="muted">Order: ${esc(w.order_status)} | Escrow: ${esc(escrowText)}</div>${w.payout_proof_url?`<div><a href="${esc(w.payout_proof_url)}" target="_blank">View payout proof</a></div>`:""}</td><td>${actions}</td></tr>`}).join("")||"<tr><td colspan='7'>No settlement records yet.</td></tr>"}
async function setPayout(wallet_id,status,proof=false){const payout_proof_url=proof?prompt("Paste payout proof URL or bank receipt image URL")||"":"";await api("/api/admin/payout-status",{method:"POST",body:JSON.stringify({wallet_id,status,payout_proof_url,note:`Admin marked payout ${status}`})});loadWallet()}
function exportSettlements(){const cols=["id","order_id","seller_id","shop_name","seller_name","bank_name","bank_account_name","bank_account_number","gross_amount","commission_rate","commission_amount","seller_earning","status","payout_proof_url","created_at"];const csv=[cols.join(",")].concat(walletExportRows.map(r=>cols.map(c=>`"${String(r[c]??"").replace(/"/g,'""')}"`).join(","))).join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));a.download=`pasarmalam-settlements-${Date.now()}.csv`;a.click()}
async function loadCampaigns(){const rows=(await api("/api/campaigns")).campaigns;tbody.innerHTML=rows.map(c=>`<tr><td>${c.id}</td><td>${esc(c.name)}</td><td>${c.type}</td><td>${esc(c.value)}</td><td><span class="tag">${c.status}</span></td></tr>`).join("")}
async function loadSettings(){const rows=(await api("/api/admin/settings")).settings;const labels={commission_rate:"Commission rate %",escrow_release:"Escrow release rule",return_window_days:"Return window days",free_shipping_budget:"Free shipping budget",late_shipment_threshold_days:"Late shipment days",payment_bank_name:"Bank name",payment_account_name:"Account name",payment_account_number:"Account number",payment_support_phone:"Support phone",payment_duitnow_note:"DuitNow note",payment_tng_note:"TNG / eWallet note"};settingsBox.innerHTML=rows.map(s=>`<label>${labels[s.key]||esc(s.key)}<input id="set_${s.key}" value="${esc(s.value)}"></label>`).join("")}
async function saveSettings(){const inputs=[...settingsBox.querySelectorAll("input")],settings={};inputs.forEach(i=>settings[i.id.replace("set_","")]=i.value);await api("/api/admin/settings",{method:"POST",body:JSON.stringify({settings})});status.textContent="Settings saved."}
async function changeAdminPassword(){await api("/api/auth/change-password",{method:"POST",body:JSON.stringify({current_password:currentPassword.value,new_password:newPassword.value})});passwordStatus.textContent="Admin password changed. Use the new password next login."}
async function loadAudit(){const rows=(await api("/api/admin/audit")).audit;tbody.innerHTML=rows.map(a=>`<tr><td>${a.id}</td><td>${a.actor_id}</td><td>${esc(a.action)}</td><td>${esc(a.target_type)} #${a.target_id}</td><td>${esc(a.note)}</td><td>${new Date((a.created_at||0)*1000).toLocaleString()}</td></tr>`).join("")}
