const API="https://pasarmalam-backend.onrender.com";
function token(){return localStorage.getItem("pm_admin_token")||localStorage.getItem("pm_token")||""}
function user(){try{return JSON.parse(localStorage.getItem("pm_admin_user")||localStorage.getItem("pm_user")||"{}")}catch{return {}}}
async function api(path,options={}){const headers={"Content-Type":"application/json",...(options.headers||{})};const t=token();if(t)headers.Authorization=`Bearer ${t}`;const r=await fetch(API+path,{...options,headers});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Request failed");return d}
function money(v){return `RM${Number(v||0).toFixed(2)}`}
function esc(v){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[m]))}
function requireAdmin(){const u=user();if(!token()||u.role!=="admin")location.href="login.html"}
async function login(){const d=await api("/api/auth/login",{method:"POST",body:JSON.stringify({email:email.value,password:password.value})});if(d.user?.role!=="admin"){status.textContent="Admin access required";return}localStorage.setItem("pm_admin_token",d.token);localStorage.setItem("pm_admin_user",JSON.stringify(d.user));location.href="index.html"}
function logout(){localStorage.removeItem("pm_admin_token");localStorage.removeItem("pm_admin_user");location.href="login.html"}
async function loadMetrics(){const m=await api("/api/admin/metrics");metrics.innerHTML=`<div class="stat"><span>Users</span><b>${m.users}</b></div><div class="stat"><span>Products</span><b>${m.products}</b></div><div class="stat"><span>Orders</span><b>${m.orders}</b></div><div class="stat"><span>Sales</span><b>${money(m.sales)}</b></div><div class="stat"><span>Buyers</span><b>${m.buyers}</b></div><div class="stat"><span>Sellers</span><b>${m.sellers}</b></div><div class="stat"><span>Returns</span><b>${m.returns}</b></div><div class="stat"><span>Campaigns</span><b>${m.campaigns}</b></div>`}
async function loadUsers(){const rows=(await api("/api/admin/users")).users;tbody.innerHTML=rows.map(u=>`<tr><td>${u.id}</td><td><b>${esc(u.name)}</b><div class="muted">${esc(u.email)}</div></td><td>${u.role}</td><td><span class="tag ${u.status==="active"?"ok":"bad"}">${u.status}</span></td><td>${u.seller_status}</td><td><button class="soft" onclick="setUser(${u.id},'active','${u.seller_status}')">Activate</button> <button class="danger" onclick="setUser(${u.id},'suspended','${u.seller_status}')">Suspend</button></td></tr>`).join("")}
async function loadSellers(){const rows=(await api("/api/admin/sellers")).sellers;tbody.innerHTML=rows.map(u=>`<tr><td>${u.id}</td><td><b>${esc(u.shop_name||u.name)}</b><div class="muted">${esc(u.email)} | ${esc(u.phone)}</div></td><td><span class="tag ${u.seller_status==="approved"?"ok":""}">${u.seller_status}</span></td><td><span class="tag ${u.status==="active"?"ok":"bad"}">${u.status}</span></td><td><button class="soft" onclick="setUser(${u.id},'active','approved')">Approve</button> <button class="danger" onclick="setUser(${u.id},'suspended','rejected')">Reject/Suspend</button></td></tr>`).join("")}
async function setUser(id,status,seller_status){await api("/api/admin/user-status",{method:"POST",body:JSON.stringify({user_id:id,status,seller_status})});location.reload()}
async function loadProducts(){const rows=(await api("/api/admin/products")).products;tbody.innerHTML=rows.map(p=>{const img=(p.images&&p.images[0])||p.image_url||"";return `<tr><td>${img?`<img class="thumb" src="${img}">`:""}<b>${esc(p.name)}</b><div class="muted">${esc(p.shop)} | ${esc(p.category)}</div></td><td>${money(p.price)}</td><td>${p.stock}</td><td>${p.condition}</td><td><span class="tag ${p.moderation_status==="approved"?"ok":"bad"}">${p.moderation_status||"approved"}</span></td><td><button class="soft" onclick="setProduct(${p.id},'approved')">Approve</button> <button class="danger" onclick="setProduct(${p.id},'hidden')">Hide</button></td></tr>`}).join("")}
async function setProduct(id,moderation_status){await api("/api/admin/product-status",{method:"POST",body:JSON.stringify({product_id:id,moderation_status})});location.reload()}
async function loadOrders(){const rows=(await api("/api/admin/orders")).orders;tbody.innerHTML=rows.map(o=>`<tr><td>PM-${o.id}</td><td>${esc(o.product_name)}<div class="muted">${esc(o.seller_shop)}</div></td><td>${esc(o.buyer_name)}</td><td>${money(o.total)}</td><td>${o.payment_status}</td><td><span class="tag">${o.order_status}</span></td><td>${esc(o.tracking_no)}</td></tr>`).join("")}
async function loadReturns(){const rows=(await api("/api/admin/returns")).returns;tbody.innerHTML=rows.map(r=>`<tr><td>${r.id}</td><td>PM-${r.order_id}<div class="muted">${esc(r.product_name||"")}</div></td><td>${esc(r.buyer_name)}</td><td>${esc(r.reason)}${r.evidence_url?`<div><a href="${r.evidence_url}" target="_blank">Evidence</a></div>`:""}</td><td><span class="tag">${r.status}</span><div class="muted">${r.dispute_status||"open"}</div></td><td><button class="soft" onclick="setReturn(${r.id},'approved','resolved')">Approve</button> <button class="danger" onclick="setReturn(${r.id},'rejected','closed')">Reject</button></td></tr>`).join("")}
async function setReturn(id,status,dispute_status){await api("/api/admin/return-status",{method:"POST",body:JSON.stringify({return_id:id,status,dispute_status,seller_response:"Admin reviewed"})});location.reload()}
async function loadWallet(){const rows=(await api("/api/wallet")).wallet;tbody.innerHTML=rows.map(w=>`<tr><td>${w.id}</td><td>${w.type}</td><td>${money(w.amount)}</td><td>${esc(w.note)}</td><td>${new Date((w.created_at||0)*1000).toLocaleString()}</td></tr>`).join("")}
async function loadCampaigns(){const rows=(await api("/api/campaigns")).campaigns;tbody.innerHTML=rows.map(c=>`<tr><td>${c.id}</td><td>${esc(c.name)}</td><td>${c.type}</td><td>${esc(c.value)}</td><td><span class="tag">${c.status}</span></td></tr>`).join("")}
