services:
  - type: web
    name: pasarmalam-landing-site
    env: static
    buildCommand: ""
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /buyer
        destination: /buyer.html
      - type: rewrite
        source: /seller
        destination: /seller.html
      - type: rewrite
        source: /policies
        destination: /policies.html
      - type: rewrite
        source: /contact
        destination: /contact.html
